### ISSUE TITLE
Possibility to change the color

### ISSUE THREAD

**Issue by mirabellette** [guildem/publicip-android#1]
Hello,

First of all, thank you very much for your application, it works perfectly well.

Is it possible to have an option to set the color of the IP address when it is displayed as a widget? The white color is not very readable when you have a light wallpaper.

Thank you,
Mirabellette

**Comment by guildem** [comment]
Thank you for using it !
The color configuration (and the text, plus some other things) is on an planned update.
I need to configure each widget separately, and to add a configuration screen on the app.

Stay tuned ! ;)

**Comment by guildem** [comment]
Hi @mirabellette , I pushed a version with title and color configuration when adding a widget.
I hope you'll find a way to configure the widget color with it.
I sent the new version to Google Play and F-Droid today.
